[build]
command = "chmod +x build.sh && ./build.sh"
publish = "build"

[build.environment]
PYTHON_VERSION = "3.10"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Permissions-Policy = "document-domain=()"
